keycloak:
  client-id: ${KEYCLOAK_CLIENT_ID}
  client-secret: ${KEYCLOAK_CLIENT_SECRET}
  host: ${KEYCLOAK_HOST:http://keycloak.internal:8443}
  realm: ${KEYCLOAK_REALM:fc3-codeflix}

rest-client:
  base-url: ${BASE_URL:http://localhost:8080}
  keycloak:
    read-timeout: 1_000

server:
  port: 8080
  undertow:
    threads:
      worker: 10
      io: 2