kafka:
  bootstrap-servers: localhost:9092

keycloak:
  client-id: fc3-app
  client-secret: seecret
  host: "http://localhost:${wiremock.server.port:8001}"
  realm: test

rest-client:
  base-url: "http://localhost:${wiremock.server.port:8001}"
  keycloak:
    read-timeout: 1000

spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: root
    password: 123456
    url: jdbc:h2:mem:adm_videos_test;MODE=MYSQL;DATABASE_TO_LOWER=TRUE # É possível persistir em um arquivo alterando "mem:adm_videos_test" para "file:./.h2/dev"
  h2:
    console:
      enabled: true
      path: /h2