kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

keycloak:
  client-id: ${KEYCLOAK_CLIENT_ID}
  client-secret: ${KEYCLOAK_CLIENT_SECRET}
  host: ${KEYCLOAK_HOST:http://keycloak.internal:8443}
  realm: ${KEYCLOAK_REALM:fc3-codeflix}

mysql:
  username: ${DATABASE_MYSQL_USERNAME:root}
  password: ${DATABASE_MYSQL_PASSWORD:123456}
  schema: subscription
  url: ${DATABASE_MYSQL_URL:localhost:3306}

rest-client:
  base-url: ${BASE_URL:http://localhost:8080}
  keycloak:
    read-timeout: 1_000

server:
  port: 8080
  undertow:
    threads:
      worker: 10
      io: 2